db:
  image: postgres:latest
api:
  build: .
  volumes:
   - .:/djangoapp
  working_dir: /djangoapp
  ports:
    - "8000:8000"
  links:
    - db
  command: /sbin/my_init
  environment:
  - PRODUCTION=False